spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_cache
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 172.20.14.197
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging.level.com.chaolong.cache.mapper: debug
debug: true



